const STORAGE_KEY = 'estudio-reels-ia-v1';
const defaults = { name: '', description: '', logo: 'R', primary: '#7657ff', accent: '#ffcf5c', background: '#1e1e2e', colorNotes: '', captionText: 'Uma ideia simples pode mudar o seu conteúdo.', captionStyle: 'impact', captionPosition: 'bottom', sources: '', references: '', tone: '', format: '9:16 · Reels vertical', editingNotes: '' };
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{"projects":[],"selectedId":null}');
const $ = id => document.getElementById(id);
const fields = { projectName:'name', projectDescription:'description', logoText:'logo', primaryColor:'primary', accentColor:'accent', backgroundColor:'background', colorNotes:'colorNotes', captionText:'captionText', captionStyle:'captionStyle', captionPosition:'captionPosition', sourcesText:'sources', referencesText:'references', tone:'tone', format:'format', editingNotes:'editingNotes' };
function current(){ return state.projects.find(p => p.id === state.selectedId); }
function persist(message='Alterações salvas automaticamente'){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); $('saveStatus').textContent=message; setTimeout(()=>{$('saveStatus').textContent='Alterações salvas automaticamente'},1800); }
function renderList(){ $('projectList').innerHTML=state.projects.map(p=>`<button class="project-item ${p.id===state.selectedId?'active':''}" data-id="${p.id}"><i class="project-dot" style="background:${p.primary}"></i><span>${escapeHtml(p.name||'Projeto sem nome')}</span></button>`).join(''); document.querySelectorAll('.project-item').forEach(b=>b.onclick=()=>{state.selectedId=b.dataset.id;persist('Projeto selecionado');render();}); }
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function render(){ const p=current(); $('emptyState').classList.toggle('hidden',!!p); $('editor').classList.toggle('hidden',!p); renderList(); if(!p)return; Object.entries(fields).forEach(([id,key])=>$(id).value=p[key]??''); updatePreview(); }
function updatePreview(){const p=current(); if(!p)return; $('previewLogo').textContent=p.logo||'R';$('previewName').textContent=p.name||'Seu projeto';$('brandPreview').style.background=p.background;$('previewLogo').style.background=p.primary;$('swatchPrimary').style.background=p.primary;$('swatchAccent').style.background=p.accent;$('swatchBackground').style.background=p.background;$('captionDisplay').textContent=p.captionText||'Sua legenda aparece aqui'; const c=$('captionPreview');c.className='caption-preview '+p.captionStyle+' '+p.captionPosition;c.style.background=`linear-gradient(145deg, ${p.background}, #0e0e16)`;c.querySelector('span').style.color=p.accent;}
function create(){ const p={...defaults,id:crypto.randomUUID()};state.projects.unshift(p);state.selectedId=p.id;persist('Novo projeto criado');render();$('projectName').focus(); }
Object.entries(fields).forEach(([id,key])=>$(id).addEventListener('input',e=>{const p=current();if(!p)return;p[key]=e.target.value;persist();renderList();updatePreview();}));
$('newProject').onclick=create;$('emptyNewProject').onclick=create;$('saveNow').onclick=()=>persist('Projeto salvo agora');
$('deleteProject').onclick=()=>{const p=current();if(p&&confirm(`Excluir “${p.name||'este projeto'}”?`)){state.projects=state.projects.filter(x=>x.id!==p.id);state.selectedId=state.projects[0]?.id||null;persist('Projeto excluído');render();}};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===t.dataset.tab));});
$('loadExample').onclick=()=>{if(state.projects.length&&!confirm('Adicionar um projeto de exemplo?'))return;const p={...defaults,id:crypto.randomUUID(),name:'Café da Marina',description:'Reels curtos para aproximar a marca da comunidade.',logo:'CM',primary:'#d7633d',accent:'#f4cf55',background:'#203c3a',captionText:'CAFÉ BOM COMEÇA COM UMA HISTÓRIA.',captionStyle:'impact',sources:'Briefing de marca e roteiro semanal.',references:'Ritmo calmo, luz natural e planos fechados.',tone:'quente, próximo e curioso',editingNotes:'Cortes suaves; destacar textura e preparo.'};state.projects.unshift(p);state.selectedId=p.id;persist('Exemplo carregado');render();};
$('clearData').onclick=()=>{if(confirm('Apagar todos os projetos salvos neste navegador?')){state={projects:[],selectedId:null};persist('Dados locais removidos');render();}};
render();
